-- ============================================================
-- BTEQ VALIDATION SQL — DEPOSIT PIPELINE
-- Run in SQL Assistant / BTEQ
-- Each SELECT returns 0 rows on PASS (violation-style checks)
-- ============================================================

/* ═══════════════════════════════════════════════════════════
   FCT_DPOS_BAL
   ═══════════════════════════════════════════════════════════ */

-- 1. Duplicate grain check (DPOS_AGMT_ID + BAL_DT)
SELECT DPOS_AGMT_ID, BAL_DT, COUNT(*) AS DUPES
FROM   EDW_FSLDM.FCT_DPOS_BAL
GROUP BY DPOS_AGMT_ID, BAL_DT
HAVING COUNT(*) > 1;

-- 2. NULL on required keys
SELECT COUNT(*) AS NULL_KEY_CNT
FROM   EDW_FSLDM.FCT_DPOS_BAL
WHERE  DPOS_AGMT_ID IS NULL OR BAL_DT IS NULL
OR     PRTY_ID IS NULL OR PROD_ID IS NULL;

-- 3. DPOS_TYP_CD valid values
SELECT DPOS_TYP_CD, COUNT(*) AS CNT
FROM   EDW_FSLDM.FCT_DPOS_BAL
WHERE  DPOS_TYP_CD NOT IN
       ('CASA_C','CASA_S','TERM_F','RECR_D','NTIC_D','CALL_D','STRC_D','ISLM_M','ISLM_W')
GROUP BY DPOS_TYP_CD;

-- 4. CASA accounts should have NULL MTRTY_DT
SELECT DPOS_AGMT_ID, DPOS_TYP_CD, MTRTY_DT
FROM   EDW_FSLDM.FCT_DPOS_BAL
WHERE  DPOS_TYP_CD IN ('CASA_C','CASA_S')
AND    MTRTY_DT IS NOT NULL;

-- 5. DAYS_TO_MTRTY_CNT must be >= 0 for active term deposits
SELECT DPOS_AGMT_ID, MTRTY_DT, DAYS_TO_MTRTY_CNT
FROM   EDW_FSLDM.FCT_DPOS_BAL
WHERE  TERM_DEPOS_IND = 'Y'
AND    MTRTY_DT IS NOT NULL
AND    DAYS_TO_MTRTY_CNT < 0;

-- 6. Islamic accounts must have ISLM_IND = 'Y'
SELECT DPOS_AGMT_ID, DPOS_TYP_CD, ISLM_IND
FROM   EDW_FSLDM.FCT_DPOS_BAL
WHERE  DPOS_TYP_CD IN ('ISLM_M','ISLM_W')
AND    ISLM_IND <> 'Y';

-- 7. CURR_BAL_AMT must be >= 0
SELECT DPOS_AGMT_ID, CURR_BAL_AMT
FROM   EDW_FSLDM.FCT_DPOS_BAL
WHERE  CURR_BAL_AMT < 0;

-- 8. AVAIL_BAL_AMT must be <= CURR_BAL_AMT
SELECT DPOS_AGMT_ID, CURR_BAL_AMT, AVAIL_BAL_AMT
FROM   EDW_FSLDM.FCT_DPOS_BAL
WHERE  AVAIL_BAL_AMT > CURR_BAL_AMT;

-- 9. Row count check — must have at least 1 row
SELECT CASE WHEN COUNT(*) = 0 THEN 'FAIL: No rows in FCT_DPOS_BAL' ELSE 'OK' END AS STATUS
FROM   EDW_FSLDM.FCT_DPOS_BAL;

-- 10. Freshness check — ETL_CRET_TS must be today
SELECT COUNT(*) AS STALE_ROW_CNT
FROM   EDW_FSLDM.FCT_DPOS_BAL
WHERE  CAST(ETL_CRET_TS AS DATE) <> CURRENT_DATE;

/* ═══════════════════════════════════════════════════════════
   FCT_DPOS_EVNT
   ═══════════════════════════════════════════════════════════ */

-- 11. Duplicate EVNT_ID
SELECT EVNT_ID, COUNT(*) AS DUPES
FROM   EDW_FSLDM.FCT_DPOS_EVNT
GROUP BY EVNT_ID
HAVING COUNT(*) > 1;

-- 12. SIGNED_AMT sign logic: Credit must be positive, Debit negative
SELECT EVNT_ID, DR_CR_IND, EVNT_AMT, SIGNED_AMT
FROM   EDW_FSLDM.FCT_DPOS_EVNT
WHERE  (DR_CR_IND = 'C' AND SIGNED_AMT < 0)
OR     (DR_CR_IND = 'D' AND SIGNED_AMT > 0);

-- 13. No reversed events should be in target
SELECT COUNT(*) AS REVRS_CNT
FROM   EDW_FSLDM.FCT_DPOS_EVNT
WHERE  REVRS_IND = 'Y';

-- 14. EVNT_TYP_CD valid values
SELECT EVNT_TYP_CD, COUNT(*) AS CNT
FROM   EDW_FSLDM.FCT_DPOS_EVNT
WHERE  EVNT_TYP_CD NOT IN
       ('DEPOS','WTHDR','INTRC','FEECD','CHGCD','TAXWH','CLSPR','RNWPR','PENLT','ISLMP')
GROUP BY EVNT_TYP_CD;

-- 15. DATA_SRC must be CURRENT or ARCHIVE only
SELECT DATA_SRC, COUNT(*) AS CNT
FROM   EDW_FSLDM.FCT_DPOS_EVNT
WHERE  DATA_SRC NOT IN ('CURRENT','ARCHIVE')
GROUP BY DATA_SRC;

-- 16. EVNT_AMT must be > 0
SELECT COUNT(*) AS NEG_AMT_CNT
FROM   EDW_FSLDM.FCT_DPOS_EVNT
WHERE  EVNT_AMT <= 0;

/* ═══════════════════════════════════════════════════════════
   FCT_INTRS_ACCRL
   ═══════════════════════════════════════════════════════════ */

-- 17. Duplicate grain (DPOS_AGMT_ID + ACCRL_DT)
SELECT DPOS_AGMT_ID, ACCRL_DT, COUNT(*) AS DUPES
FROM   EDW_FSLDM.FCT_INTRS_ACCRL
GROUP BY DPOS_AGMT_ID, ACCRL_DT
HAVING COUNT(*) > 1;

-- 18. NET_ACCRL_AMT = GROSS_ACCRL_AMT - TAX_WTHHD_AMT
SELECT DPOS_AGMT_ID, ACCRL_DT,
       GROSS_ACCRL_AMT, TAX_WTHHD_AMT, NET_ACCRL_AMT
FROM   EDW_FSLDM.FCT_INTRS_ACCRL
WHERE  ABS(NET_ACCRL_AMT - (GROSS_ACCRL_AMT - TAX_WTHHD_AMT)) > 0.01;

-- 19. ACCRL_AMT must be >= 0
SELECT COUNT(*) AS NEG_ACCRL_CNT
FROM   EDW_FSLDM.FCT_INTRS_ACCRL
WHERE  ACCRL_AMT < 0;

-- 20. Cumulative MTD must be >= daily accrual
SELECT DPOS_AGMT_ID, ACCRL_DT, ACCRL_AMT, CUMUL_ACCRL_AMT_MTD
FROM   EDW_FSLDM.FCT_INTRS_ACCRL
WHERE  CUMUL_ACCRL_AMT_MTD < ACCRL_AMT;

-- 21. YTD cumulative must be >= MTD cumulative
SELECT DPOS_AGMT_ID, ACCRL_DT, CUMUL_ACCRL_AMT_MTD, CUMUL_ACCRL_AMT_YTD
FROM   EDW_FSLDM.FCT_INTRS_ACCRL
WHERE  CUMUL_ACCRL_AMT_YTD < CUMUL_ACCRL_AMT_MTD;

-- 22. ACCRL_MTHD_CD valid values
SELECT ACCRL_MTHD_CD, COUNT(*) AS CNT
FROM   EDW_FSLDM.FCT_INTRS_ACCRL
WHERE  ACCRL_MTHD_CD NOT IN ('ACT365','ACT360','30360')
GROUP BY ACCRL_MTHD_CD;
