"""dev_agent.py — Stage 3: emit Teradata SQL + dbt models from MappingSpec."""
from __future__ import annotations
from pathlib import Path

from agents.state import SDLCState, Artifact, MappingSpec

ROOT = Path(__file__).parent.parent


def _render_sql(spec: MappingSpec, target) -> str:
    cols = ",\n  ".join(f"{fm.source_expr} AS {fm.target_column}" for fm in target.field_mappings)
    src_tables = sorted({t for fm in target.field_mappings for t in fm.source_tables})
    from_clause = src_tables[0] if src_tables else "DPOS_AGMT"
    joins = "\n".join(
        f"LEFT JOIN {t} ON 1=1 /* TODO join key */" for t in src_tables[1:]
    )
    return (
        f"-- Generated by FSLDM SDLC Dev Agent\n"
        f"-- Target: {target.target_table}  Grain: {target.grain_description}\n"
        f"-- Dialect: {spec.dialect}  Mapping: {spec.mapping_id}\n\n"
        f"INSERT INTO EDW_FSLDM.{target.target_table}\n"
        f"SELECT\n  {cols}\nFROM {from_clause}\n{joins};\n"
    )


def _render_dbt_model(spec: MappingSpec, target) -> str:
    cols = ",\n  ".join(f"{fm.source_expr} AS {fm.target_column}" for fm in target.field_mappings)
    return (
        "{{ config(materialized='table') }}\n\n"
        f"-- {target.target_table} — {target.grain_description}\n"
        f"SELECT\n  {cols}\nFROM {{{{ source('ods','DPOS_AGMT') }}}}\n"
    )


def _render_dbt_schema(spec: MappingSpec) -> str:
    lines = ["version: 2", "", "models:"]
    for t in spec.target_tables:
        lines.append(f"  - name: {t.target_table.lower()}")
        lines.append(f"    description: \"{t.grain_description}\"")
        lines.append("    columns:")
        for fm in t.field_mappings[:8]:
            lines.append(f"      - name: {fm.target_column.lower()}")
    return "\n".join(lines) + "\n"


def dev_node(state: SDLCState) -> dict:
    spec: MappingSpec = state.get("mapping")  # type: ignore
    if not spec:
        return {"errors": state.get("errors", []) + ["dev_node: missing mapping"]}

    artifacts: list[Artifact] = []
    dialect = spec.dialect

    out_sql_dir = ROOT / ("sql_teradata" if dialect == "teradata" else f"sql_{dialect}_gen")
    out_dbt_dir = ROOT / "sql_dbt_gen"
    out_sql_dir.mkdir(exist_ok=True)
    out_dbt_dir.mkdir(exist_ok=True)

    for t in spec.target_tables:
        sql = _render_sql(spec, t)
        p = out_sql_dir / f"{t.target_table.lower()}.gen.sql"
        p.write_text(sql, encoding="utf-8")
        artifacts.append(Artifact(
            path=str(p.relative_to(ROOT)),
            kind="sql",
            dialect=dialect,
            target_table=t.target_table,
            bytes_written=len(sql),
        ))

        dbt = _render_dbt_model(spec, t)
        p2 = out_dbt_dir / f"{t.target_table.lower()}.sql"
        p2.write_text(dbt, encoding="utf-8")
        artifacts.append(Artifact(
            path=str(p2.relative_to(ROOT)),
            kind="dbt",
            dialect="snowflake",
            target_table=t.target_table,
            bytes_written=len(dbt),
        ))

    schema_yml = _render_dbt_schema(spec)
    p3 = out_dbt_dir / "schema.gen.yml"
    p3.write_text(schema_yml, encoding="utf-8")
    artifacts.append(Artifact(
        path=str(p3.relative_to(ROOT)),
        kind="yaml",
        bytes_written=len(schema_yml),
    ))

    return {"artifacts": artifacts}
